// This file is auto-generated by scripts/gen-math-config.mjs. DO NOT EDIT.
export const customMacros = {
  "\\real": "\\mathbb{R}",
  "\\cmplx": "\\mathbb{C}",
  "\\pab": [
    "\\\\left( #1 \\\\right)",
    1
  ],
  "\\bab": [
    "\\\\left[ #1 \\\\right]",
    1
  ],
  "\\fdif": [
    "\\\\delta #1",
    1
  ],
  "\\odif": [
    "d #1",
    1
  ]
};
